"""tutor: case_text + speaking_score

Revision ID: 433f7ef2f43b
Revises: e5707ecfadca
Create Date: 2026-06-20 12:54:33.429318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433f7ef2f43b'
down_revision: Union[str, None] = 'e5707ecfadca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_profiles', sa.Column('case_text', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('speaking_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'speaking_score')
    op.drop_column('learning_profiles', 'case_text')
    # ### end Alembic commands ###
