"""teacher admin_note

Revision ID: a5fb2003fcc3
Revises: 74b535dffa1d
Create Date: 2026-06-20 19:12:59.924166
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fb2003fcc3'
down_revision: Union[str, None] = '74b535dffa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_applications', sa.Column('admin_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_applications', 'admin_note')
    # ### end Alembic commands ###
