"""homework submission_file

Revision ID: baf960f05733
Revises: ad111ad75458
Create Date: 2026-06-21 05:53:08.865487
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf960f05733'
down_revision: Union[str, None] = 'ad111ad75458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('submission_file', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'submission_file')
    # ### end Alembic commands ###
