"""ai tutor: profiles, tasks, sessions, turns, results

Revision ID: e5707ecfadca
Revises: 117c7ad8b448
Create Date: 2026-06-20 11:39:21.736539
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5707ecfadca'
down_revision: Union[str, None] = '117c7ad8b448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.String(length=40), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('contexts', sa.JSON(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_profiles_user_id'), 'learning_profiles', ['user_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=300), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='taskdifficulty'), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', name='taskstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', name='sessionstatus'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_task_id'), 'tutor_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_tutor_sessions_user_id'), 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('task_score', sa.Integer(), nullable=False),
    sa.Column('language_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_session_id'), 'results', ['session_id'], unique=True)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'ai', name='turnrole'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_seconds', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_results_session_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_tutor_sessions_user_id'), table_name='tutor_sessions')
    op.drop_index(op.f('ix_tutor_sessions_task_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_learning_profiles_user_id'), table_name='learning_profiles')
    op.drop_table('learning_profiles')
    # ### end Alembic commands ###
